id = "tiniri"
name = "Tiniri"
schema_version = 1
version = "0.0.2"
authors = ["Vlad Gerasimov <vlad@vlad.studio>"]
description = "Calm and cozy color themes with warm, desaturated colors in light and dark variants"
repository = "https://github.com/vladstudio/tiniri-zed"
